# Generated by Django 5.0.6 on 2024-08-14 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('place', models.CharField(max_length=255)),
                ('start', models.DateTimeField(verbose_name='Начало события')),
                ('stop', models.DateTimeField(verbose_name='Окончание события')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(blank=True, upload_to='events/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_event', to=settings.AUTH_USER_MODEL, verbose_name='Автор события')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='bot.groupbot', verbose_name='Телеграмм бот, обслуживающий событие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Событие')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Приглашенный на событие',
                'verbose_name_plural': 'Приглашенные на событие',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='guest',
            field=models.ManyToManyField(blank=True, related_name='guest_event', through='events.EventGuest', to=settings.AUTH_USER_MODEL, verbose_name='Участвники события'),
        ),
        migrations.CreateModel(
            name='SamplePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_start', models.DateTimeField(verbose_name='Начало выборки в чате телеграмма')),
                ('t_stop', models.DateTimeField(verbose_name='Конец выборки в чате телеграмма')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Период выборки',
                'verbose_name_plural': 'Периоды выборки',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventguest',
            constraint=models.UniqueConstraint(fields=('event', 'guest'), name='event_guest_index'),
        ),
    ]
