# Generated by Django 5.0.6 on 2024-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventguest',
            options={'ordering': ['-pk'], 'verbose_name': 'Приглашенный на событие', 'verbose_name_plural': 'Приглашенные на событие'},
        ),
        migrations.AlterModelOptions(
            name='sampleperiod',
            options={'ordering': ['-pk'], 'verbose_name': 'Период выборки', 'verbose_name_plural': 'Периоды выборки'},
        ),
        migrations.RemoveField(
            model_name='sampleperiod',
            name='start',
        ),
        migrations.RemoveField(
            model_name='sampleperiod',
            name='stop',
        ),
        migrations.AddField(
            model_name='sampleperiod',
            name='t_start',
            field=models.DateTimeField(auto_now=True, verbose_name='Начало выборки в чате телеграмма'),
        ),
        migrations.AddField(
            model_name='sampleperiod',
            name='t_stop',
            field=models.DateTimeField(auto_now=True, verbose_name='Конец выборки в чате телеграмма'),
        ),
    ]
