# Generated by Django 5.0.6 on 2024-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventguest_options_alter_sampleperiod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(verbose_name='Начало события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stop',
            field=models.DateField(verbose_name='Окончание события'),
        ),
    ]
