# Generated by Django 5.0.6 on 2024-08-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('events', '0003_alter_event_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='bot.groupbot', verbose_name='Телеграмм бот, обслуживающий событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_event', to=settings.AUTH_USER_MODEL, verbose_name='Автор события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guest',
            field=models.ManyToManyField(blank=True, related_name='guest_event', through='events.EventGuest', to=settings.AUTH_USER_MODEL, verbose_name='Участвники события'),
        ),
    ]
