# Generated by Django 5.0.6 on 2024-07-29 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_start_alter_event_stop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventguest',
            constraint=models.UniqueConstraint(fields=('event', 'guest'), name='event_guest_index'),
        ),
    ]
