# Generated by Django 5.0.6 on 2024-07-28 08:06

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.core.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/users/foto/'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='signer_password',
            field=models.TextField(blank=True, verbose_name='Хэш пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='t_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Telegram id'),
        ),
        migrations.AddField(
            model_name='user',
            name='t_nick',
            field=models.CharField(blank=True, max_length=150, verbose_name='Telegram nickname'),
        ),
    ]
