# Generated by Django 5.0.6 on 2024-07-30 05:32

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_user_confirmation_code_user_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.svg', upload_to=apps.core.models.images_avatar_path),
        ),
    ]
