# Generated by Django 5.0.6 on 2024-07-30 12:40

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.webp', upload_to=apps.core.models.images_avatar_path),
        ),
    ]
