# Generated by Django 5.0.6 on 2024-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя телеграмм бота')),
                ('description', models.TextField(verbose_name='Описание телеграмм бота')),
                ('token', models.CharField(max_length=200, verbose_name='Токен телеграмм бота')),
                ('group_id', models.CharField(max_length=200, verbose_name='id группы в телеграмме, к которой поключен бот')),
                ('active', models.BooleanField(default=True, verbose_name='Признак активации бота')),
            ],
            options={
                'verbose_name': 'Телеграмм бот',
                'verbose_name_plural': 'Телеграмм боты',
                'ordering': ['-pk'],
            },
        ),
    ]
