# Generated by Django 5.0.6 on 2024-08-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('folder', models.CharField(max_length=100)),
                ('type_gpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='bot.typegpt', verbose_name='Тип ассистента')),
            ],
            options={
                'verbose_name': 'Ассистент',
                'verbose_name_plural': 'Ассистенты',
            },
        ),
    ]
