# Generated by Django 5.0.6 on 2024-08-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_typegpt_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbot',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_bot', to='bot.assistant', verbose_name='Ассистент'),
        ),
    ]
